### ISSUE TITLE
export 'default' (imported as 'e') was not found in 'single-spa'

### ISSUE THREAD

**Issue by celian-garcia** [single-spa/single-spa-layout#93]
Hello, @joeldenning did the 1.1.5 fixed the issue #90 ?
I mean I am trying single-spa-layout in my project
```json
  "dependencies": {
    "single-spa": "5.8.1",
    "single-spa-layout": "^1.1.5"
  },
```
```typescript
import { registerApplication, start } from 'single-spa';
import { constructApplications, constructLayoutEngine, constructRoutes } from 'single-spa-layout';
```
And I am facing a similar issue

```
ERROR in ./node_modules/single-spa-layout/dist/esm/single-spa-layout.min.js 2:2995-3021
export 'default' (imported as 'e') was not found in 'single-spa' (possible exports: BOOTSTRAPPING, LOADING_SOURCE_CODE, LOAD_ERROR, MOUNTED, MOUNTING, NOT_BOOTSTRAPPED, NOT_LOADED, NOT_MOUNTED, SKIP_BECAUSE_BROKEN, UNMOUN
TING, UPDATING, addErrorHandler, checkActivityFunctions, ensureJQuerySupport, getAppNames, getAppStatus, getMountedApps, mountRootParcel, navigateToUrl, pathToActiveWhen, registerApplication, removeErrorHandler, setBootst
rapMaxTime, setMountMaxTime, setUnloadMaxTime, setUnmountMaxTime, start, triggerAppChange, unloadApplication, unregisterApplication)
```

**Comment by celian-garcia** [comment]
I found a workaround using require but it would be nice to make the esm work.

Workaround to not use esm :
```typescript
import { registerApplication, start } from 'single-spa';
// import { constructApplications, constructLayoutEngine, constructRoutes } from 'single-spa-layout';
const singleSpaLayout = require('single-spa-layout');
```

Investigation :
It seems that esm lib is containing an import * as e from "single-spa" which is not appreciated by single-spa
![image](https://user-images.githubusercontent.com/10258608/98459858-250c1e80-219f-11eb-8952-9b2b9cea55e6.png)

**Comment by joeldenning** [comment]
This is a duplicate of https://github.com/single-spa/single-spa-layout/issues/93

**Comment by joeldenning** [comment]
Fix released in https://github.com/single-spa/single-spa-layout/releases/tag/v1.1.6

**Comment by celian-garcia** [comment]
Hello, @joeldenning thanks for the update, actually I checked this morning and the issue is still there.

I checked exactly the same thing 
```
import { constructApplications, constructLayoutEngine, constructRoutes } from 'single-spa-layout';
```
And the start give me this error
```
ERROR in ./node_modules/single-spa-layout/dist/esm/single-spa-layout.min.js 2:3026-3052
export 'default' (imported as 'e') was not found in 'single-spa' (possible exports: BOOTSTRAPPING, LOADING_SOURCE_CODE, LOAD_ERROR, MOUNTED, MOUNTING, NOT_BOOTSTRAPPED, NOT_LOADED, NOT_MOUNTED, SKIP_BECAUSE_BROKEN, UNMOUN
TING, UPDATING, addErrorHandler, checkActivityFunctions, ensureJQuerySupport, getAppNames, getAppStatus, getMountedApps, mountRootParcel, navigateToUrl, pathToActiveWhen, registerApplication, removeErrorHandler, setBootst
rapMaxTime, setMountMaxTime, setUnloadMaxTime, setUnmountMaxTime, start, triggerAppChange, unloadApplication, unregisterApplication)
 @ ./src/main.ts 2:0-98 14:17-32 15:23-44 22:23-44

```
![image](https://user-images.githubusercontent.com/10258608/99180071-885bfa80-2723-11eb-8625-6f6f6c36ae79.png)

I'm starting to think it's coming from my typescript configuration... I'll check

**Comment by celian-garcia** [comment]
After some search, I don't think it is coming from my tsconfig. 

I found that in the ``constructRoutes.js`` you are using :
```
import * as singleSpa from "single-spa";
```
I think this is the line translated in ``import * as e from "single-spa"`` in the minified esm code.

I think also that ``import *`` implies that single-spa has a ``default`` instruction in the code, and it doesn't. 

Am I right ? I'm not sure of what I'm saying and I don't understand enough the ``pathToActiveWhen`` dynamic import thingy that you are performing to try myself. I just hope that it helps...

Happy digging 😅

**Comment by joeldenning** [comment]
Please provide a demonstration of the issue.

**Comment by celian-garcia** [comment]
Okay I'll build a minimal reproduction

**Comment by jsmapr1** [comment]
I'm having the same issue. Minimal reproducable example here: https://github.com/jsmapr1/single-spa-layout-minimal

`npm run build` will trigger the error.

Can confirm that using `require` works fine.

**Comment by joeldenning** [comment]
Please open a new issue, as this one was already solved. Also, is this specific to using webpack 5? Or does it also happen with webpack 4?
